### ISSUE TITLE
Repository to be usable in smart contracts

### ISSUE THREAD

**Issue by NikolayKostadinov21** [noir-lang/noir-bignum#146]
### Problem

I am trying to use the `noir-bignum` repo in a smart contract but I am unable to compile, even with the (currently) newest versions of the compiler and the version of the repo.
- compiler version - `v1.0.0-beta.3`.
- repo version - `v0.6.0`

### Happy Case

Being able to use the repo in smart contracts. Currently, I am facing the issue of not being able to use larger numbers than `u64` and only this repo is able to help.

### Workaround

None

### Project Impact

Blocker

### Blocker Context

E.g cannot divide `1 / TWO_POW_128` because the largest type that can be used in smart contracts is `u64`.  This creates a big blocker because `Field` types are field elements and are not meant for arbitrary operations

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Hey Nikolay, thanks for opening this issue. Can you provide an example of how you're using this library so we can see the issues you're running into more clearly?

**Comment by NikolayKostadinov21** [comment]
@TomAFrench, so I am trying to use `div` and `mod` operations for numbers larger than `2^128` in **smart contracts** and in particular when the `denumerator > numerator`. I don't have any issues with what I want to achieve in a circuit (the same business logic) but regarding contracts, I get 361 errors. To reproduce it, you can try to have the bignum library as a dependency in a smart contract and try to compile.
As for the errors, (some of them are repetitive), they include:
```
    │
253 │         validate_in_range::<_, _, MOD_BITS>(self.limbs);
    │         ----------------------------------- Type must be known by this point to know which method to call
```
```
149 │     let mut lhs: [[u128; N]; NUM_PRODUCTS] = [[0; N]; NUM_PRODUCTS];
    │                    ---- Allowed bit sizes for integers are 1, 8, 32, 64
```
```
    │
337 │     let is_one = t2m == one;
    │                  ---------- No impl for `T: Eq`
    │
```

where the `Allowed bit sizes for integers are 1, 8, 32, 64`  error is present in the ~85% of the errors and IMO it's because the limbs of the u256 struct are of type `u128` and the allowed types in smart contracts are not bigger than `u128`. But if that's the case, this imposes the limitation of not being able to have even calculations of larger numbers in smart contracts.

`Type must be known by this point to know which method to call` is ~10% of the errors, and ` No impl for `T: Eq`` ~5% of the errors.

**Comment by TomAFrench** [comment]
@NikolayKostadinov21 I'm aware that you're trying to compile for a smart contract. I'm asking for a reproduction of your issue as it's very likely to be an configuration issue where you're compiling with two different versions of nargo for programs and contracts and I want to avoid us talking past each other.

Please provide a repository which I can clone and compile with nargo 1.0.0-beta.3 (as installed from `noirup -v 1.0.0-beta.3) to reproduce the issue you're experiencing.

**Comment by NikolayKostadinov21** [comment]
@TomAFrench Sure, there it is: https://github.com/NikolayKostadinov21/aztec-nr-experiments/tree/main/empty_contract
It's just an empty contract.

**Comment by TomAFrench** [comment]
Ok, thank you. If I run `nargo compile` with noir 1.0.0-beta.3 on that project then I get no compilation errors.

**Comment by TomAFrench** [comment]
If you're installing nargo through any tool other than through `noirup` then the versioning cannot be trusted to align with the versions against which this library is tested.

**Comment by NikolayKostadinov21** [comment]
@TomAFrench I get it, I also have no issues running `nargo compile`, the thing is that I am trying to compile a contract which uses different tool which is `aztec-nargo`. So can we conclude then that the bignum repository isn't suitable for smart contracts?

**Comment by TomAFrench** [comment]
aztec-nargo is just a shell script around nargo which is released on a different schedule than "real" nargo so any library which is supported in the real nargo will eventually work in `aztec-nargo` as changes filter through. However,  `aztec-nargo` can then have multiple releases which report that they're `nargo 1.0.0-beta.3` but none of them will be really `nargo 1.0.0-beta.3` as it's built from a different commit in a different repository which causes issues like this.

https://github.com/AztecProtocol/aztec-packages/tree/master/aztec-nargo

Any noir library will be tested against the mainline nargo releases as made in https://github.com/noir-lang/noir.
